var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/customer-galleries/[slug]/payment/route.js")
R.c("server/chunks/[root-of-the-server]__0nj99x8._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/[root-of-the-server]__0o62aiz._.js")
R.c("server/chunks/node_modules_0t08xuk._.js")
R.c("server/chunks/src_lib_supabase_admin_ts_0cfteh4._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/1oeh_server_app_api_customer-galleries_[slug]_payment_route_actions_0rn1ei8.js")
R.m(64396)
module.exports=R.m(64396).exports
