var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin-studio/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__05aly56._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1l86z-v.js")
R.c("server/chunks/ssr/node_modules_next_17sz44y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1h4k0e-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/node_modules_@supabase_supabase-js_dist_index_mjs_087pi7g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__186sgu7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1map00z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06agv4m._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin-studio_page_actions_0hl_6b9.js")
R.m(83782)
module.exports=R.m(83782).exports
