import { ArrowRight } from "lucide-react";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { RentalProductCard } from "@/components/rental/rental-product-card";
import { rentalProducts } from "@/lib/rental/catalog";

export const metadata: Metadata = { title: "Thuê Trang Phục | TLORA Studio", description: "Trang phục và phụ kiện được tuyển chọn cho concept, thời trang và nghệ thuật." };
export default function RentalLandingPage() { return <><section className="relative flex min-h-[82svh] items-end overflow-hidden px-5 pb-14 pt-28 sm:px-8 sm:pb-20 lg:px-10"><Image src="/concept/concept-02.webp" alt="Trang phục concept TLORA" fill priority sizes="100vw" className="object-cover object-[50%_28%]" /><div className="absolute inset-0 bg-linear-to-t from-[#080a0f] via-[#080a0f]/20 to-black/45" /><div className="relative mx-auto w-full max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f3d88e]">TLORA Rental</p><h1 className="mt-5 max-w-[11ch] text-[clamp(3rem,12vw,7rem)] font-semibold leading-[.98] tracking-[-.055em]">Biến mọi concept trở nên hoàn hảo.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-white/65 sm:text-base">Hàng trăm trang phục, phụ kiện được tuyển chọn dành riêng cho các bộ ảnh concept, thời trang và nghệ thuật.</p><Link href="/thue-trang-phuc/san-pham" className="mt-8 inline-flex min-h-13 items-center gap-3 bg-[#f8f5ee] px-6 text-sm font-bold text-black">Xem trang phục <ArrowRight size={17}/></Link></div></section><section className="mx-auto max-w-[1500px] px-4 py-20 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-5 border-b border-white/10 pb-5"><div><p className="text-xs uppercase tracking-[.16em] text-white/40">Selected rental</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Trang phục nổi bật</h2></div><Link href="/thue-trang-phuc/san-pham" className="text-xs font-bold text-[#f3d88e]">Xem tất cả</Link></div><div className="mt-8 grid grid-cols-2 gap-x-3 gap-y-6 sm:gap-x-6 lg:grid-cols-4">{rentalProducts.slice(0,4).map((product,index)=><RentalProductCard key={product.id} product={product} priority={index<2}/>)}</div><div className="mt-16 grid gap-3 border-t border-white/10 pt-8 sm:grid-cols-2"><Link href="/thue-trang-phuc/tra-cuu" className="flex min-h-16 items-center justify-between border border-white/10 px-5 text-sm font-semibold">Tra cứu đơn <ArrowRight size={16}/></Link><Link href="/thue-trang-phuc/chinh-sua" className="flex min-h-16 items-center justify-between border border-white/10 px-5 text-sm font-semibold">Chỉnh sửa đơn đã thanh toán <ArrowRight size={16}/></Link></div></section></>; }
