"use client";
import { Copy, Download, Plus, X } from "lucide-react";
import { useState } from "react";
type UserRow = { user_id: string; username: string; display_name: string; backup_email: string | null; postCount: number };
type Credentials = { name: string; username: string; password: string; backupEmail: string };
export function TloraUsersManager({ initialUsers }: { initialUsers: UserRow[] }) {
  const [users, setUsers] = useState(initialUsers); const [open,setOpen]=useState(false); const [form,setForm]=useState({name:"",backupEmail:"",account:""}); const [credentials,setCredentials]=useState<Credentials|null>(null); const [selected,setSelected]=useState<string[]>([]); const [message,setMessage]=useState("");
  async function create() { const response=await fetch("/api/admin/tlora/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const result=await response.json() as {credentials?:Credentials;error?:string}; if(!response.ok||!result.credentials)return setMessage(result.error||"Không thể tạo người dùng."); setCredentials(result.credentials); const refreshed=await fetch("/api/admin/tlora/users"); const data=await refreshed.json() as {users:UserRow[]}; setUsers(data.users); }
  function download() { if(!credentials)return; const text=`Tên: ${credentials.name}\nTài khoản: ${credentials.username}\nMật khẩu: ${credentials.password}\nEmail backup: ${credentials.backupEmail}\n\nĐịnh dạng: ${credentials.username}|${credentials.password}`; const url=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"})); const a=document.createElement("a");a.href=url;a.download=`${credentials.username}.txt`;a.click();URL.revokeObjectURL(url); }
  return <main className="min-h-screen bg-[#f4f4f2] p-6 text-zinc-950"><header className="flex justify-between gap-4"><div><h1 className="text-3xl font-extrabold">Người dùng</h1><p className="mt-2 text-sm text-zinc-600">Quản lý tài khoản tham gia biên tập nội dung TLORA.</p></div><button onClick={()=>setOpen(true)} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-zinc-950 px-4 text-sm font-bold text-white"><Plus size={17}/>Thêm người dùng</button></header><div className="mt-6 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-zinc-50"><tr><th className="p-4"><input type="checkbox" onChange={e=>setSelected(e.target.checked?users.map(u=>u.user_id):[])} /></th><th>Tên người dùng</th><th>Tên</th><th>Email backup</th><th>Số lượng bài viết</th></tr></thead><tbody className="divide-y">{users.map(user=><tr key={user.user_id}><td className="p-4"><input type="checkbox" checked={selected.includes(user.user_id)} onChange={e=>setSelected(current=>e.target.checked?[...current,user.user_id]:current.filter(id=>id!==user.user_id))}/></td><td className="font-mono font-bold">{user.username}</td><td>{user.display_name}</td><td>{user.backup_email||"—"}</td><td>{user.postCount}</td></tr>)}</tbody></table></div>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><section className="w-full max-w-lg rounded-xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Thêm người dùng</h2><button onClick={()=>setOpen(false)}><X/></button></div>{credentials?<div className="mt-5 space-y-3"><Credential label="Tài khoản" value={credentials.username}/><Credential label="Mật khẩu" value={credentials.password}/><p className="text-xs text-zinc-500">Định dạng: {credentials.username}|{credentials.password}</p><button onClick={download} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-md bg-zinc-950 font-bold text-white"><Download size={17}/>Tải file TXT</button></div>:<div className="mt-5 space-y-4"><Field label="Tên" value={form.name} onChange={name=>setForm(c=>({...c,name}))}/><Field label="Email backup" value={form.backupEmail} onChange={backupEmail=>setForm(c=>({...c,backupEmail}))}/><label className="block text-sm font-bold">Tài khoản<div className="mt-2 flex min-h-11 items-center rounded-md border px-3"><span className="text-zinc-500">tlora.</span><input value={form.account} onChange={e=>setForm(c=>({...c,account:e.target.value}))} className="min-w-0 flex-1 outline-none"/></div></label>{message&&<p className="text-sm text-red-600">{message}</p>}<button disabled={!form.name||!form.account} onClick={create} className="min-h-11 w-full rounded-md bg-[#d8b766] font-bold disabled:opacity-40">Tạo tài khoản và mật khẩu</button></div>}</section></div>}</main>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-sm font-bold">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-11 w-full rounded-md border px-3 font-normal"/></label>}
function Credential({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold text-zinc-500">{label}</p><div className="mt-1 flex items-center rounded-md border bg-zinc-50 px-3"><code className="flex-1 py-3">{value}</code><button onClick={()=>navigator.clipboard.writeText(value)}><Copy size={16}/></button></div></div>}
