import { NextResponse } from "next/server";
import { z } from "zod";
import { RENTAL_ENABLED } from "@/lib/rental/config";
import { canonicalRentalItems, publicRentalOrder, rentalTotals, type CanonicalRentalItem } from "@/lib/rental/orders";
import { createAdminClient } from "@/lib/supabase/admin";

const editSchema=z.object({items:z.array(z.object({productId:z.string(),size:z.string(),color:z.string(),quantity:z.number().int().min(1).max(5)})).min(1).max(20)});
async function findOrder(orderCode:string){const admin=createAdminClient();const {data,error}=await admin.from("rental_orders").select("*").eq("order_code",orderCode.toUpperCase()).maybeSingle();if(error)throw error;return {admin,data};}
export async function GET(_:Request,{params}:{params:Promise<{orderCode:string}>}){try{if(!RENTAL_ENABLED)return NextResponse.json({error:"Module đã tắt."},{status:404});const {orderCode}=await params;const {data}=await findOrder(orderCode);if(!data)return NextResponse.json({error:"Không tìm thấy đơn hàng."},{status:404});return NextResponse.json({order:publicRentalOrder(data)});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Không tra cứu được đơn."},{status:500});}}
export async function PATCH(request:Request,{params}:{params:Promise<{orderCode:string}>}){try{if(!RENTAL_ENABLED)return NextResponse.json({error:"Module đã tắt."},{status:404});const {orderCode}=await params;const input=editSchema.parse(await request.json());const {admin,data}=await findOrder(orderCode);if(!data)return NextResponse.json({error:"Không tìm thấy đơn hàng."},{status:404});if(data.status!=="paid")return NextResponse.json({error:"Chỉ đơn đã thanh toán mới được chỉnh sửa."},{status:409});const previous=(data.items||[]) as CanonicalRentalItem[];const next=canonicalRentalItems(input.items);const previousCostumes=previous.filter((item)=>item.type==="costume");const nextCostumes=next.filter((item)=>item.type==="costume");if(previousCostumes.length===1&&nextCostumes.length<1)return NextResponse.json({error:"Đơn có một trang phục nên không thể xoá."},{status:400});const previousIds=new Set(previousCostumes.map((item)=>item.productId));if(nextCostumes.some((item)=>!previousIds.has(item.productId)))return NextResponse.json({error:"Không thể thêm trang phục mới khi chỉnh đơn."},{status:400});const removed=previousCostumes.length-nextCostumes.length;if(removed<0||removed>1||Number(data.removed_costume_count||0)+removed>1)return NextResponse.json({error:"Chỉ được xoá tối đa một trang phục."},{status:400});const totals=rentalTotals(next,Number(data.duration_days),String(data.promo_code||""));const {error}=await admin.from("rental_orders").update({items:next,subtotal_vnd:totals.beforeDiscount,discount_vnd:totals.discount,total_vnd:totals.total,deposit_vnd:totals.deposit,remaining_vnd:Math.max(totals.total-Number(data.paid_deposit_vnd||0),0),removed_costume_count:Number(data.removed_costume_count||0)+removed,updated_at:new Date().toISOString()}).eq("id",data.id);if(error)throw error;await admin.from("rental_order_edits").insert({order_id:data.id,before_items:previous,after_items:next,before_total_vnd:data.total_vnd,after_total_vnd:totals.total});return NextResponse.json({ok:true});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Dữ liệu chỉnh sửa chưa hợp lệ."},{status:400});return NextResponse.json({error:error instanceof Error?error.message:"Không chỉnh được đơn."},{status:500});}}
