var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/customer-galleries/[slug]/download/route.js")
R.c("server/chunks/[root-of-the-server]__1zkqjku._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/[root-of-the-server]__1p15rfp._.js")
R.c("server/chunks/src_lib_supabase_admin_ts_0cfteh4._.js")
R.c("server/chunks/[root-of-the-server]__1na7ikm._.js")
R.c("server/chunks/node_modules_1zsmeuj._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/1oeh_server_app_api_customer-galleries_[slug]_download_route_actions_0lqcyw5.js")
R.m(74405)
module.exports=R.m(74405).exports
