"use client";

import { SlidersHorizontal, X } from "lucide-react";
import { useMemo, useState } from "react";
import { rentalCategories, rentalProducts, rentalSizes, rentalStatusMeta } from "@/lib/rental/catalog";
import { RentalProductCard } from "./rental-product-card";

export function RentalCatalog() {
  const [drawer, setDrawer] = useState(false);
  const [category, setCategory] = useState("Tất cả");
  const [maxPrice, setMaxPrice] = useState(700000);
  const [color, setColor] = useState("Tất cả");
  const [size, setSize] = useState("Tất cả");
  const [status, setStatus] = useState("Tất cả");
  const colors = [...new Set(rentalProducts.map((item) => item.color))];
  const products = useMemo(() => rentalProducts.filter((item) => (category === "Tất cả" || item.category === category) && item.price <= maxPrice && (color === "Tất cả" || item.color === color) && (size === "Tất cả" || item.sizes.includes(size)) && (status === "Tất cả" || item.status === status)), [category, maxPrice, color, size, status]);
  const filters = <FilterFields category={category} setCategory={setCategory} maxPrice={maxPrice} setMaxPrice={setMaxPrice} color={color} setColor={setColor} size={size} setSize={setSize} status={status} setStatus={setStatus} colors={colors} />;
  return <div className="mx-auto max-w-[1500px] px-4 pb-24 pt-8 sm:px-6 lg:px-8"><div className="mb-8 flex items-center justify-between border-b border-white/10 pb-5"><p className="text-xs uppercase tracking-[.14em] text-white/45">{products.length} thiết kế</p><button onClick={() => setDrawer(true)} className="inline-flex min-h-11 items-center gap-2 border border-white/15 px-4 text-xs font-bold uppercase tracking-[.1em] lg:hidden"><SlidersHorizontal size={16} /> Bộ lọc</button></div><div className="grid gap-8 lg:grid-cols-[230px_1fr]"><aside className="hidden lg:block"><div className="sticky top-24">{filters}</div></aside><div className="grid grid-cols-2 gap-x-3 gap-y-5 sm:gap-x-6 lg:grid-cols-3 xl:grid-cols-4">{products.map((product, index) => <RentalProductCard key={product.id} product={product} priority={index < 4} />)}{!products.length && <p className="col-span-full py-24 text-center text-sm text-white/45">Không tìm thấy trang phục phù hợp.</p>}</div></div>{drawer && <div className="fixed inset-0 z-[80] lg:hidden"><button aria-label="Đóng bộ lọc" onClick={() => setDrawer(false)} className="absolute inset-0 bg-black/70" /><aside className="absolute inset-y-0 right-0 w-[88%] max-w-sm overflow-y-auto bg-[#0d0f13] p-6 shadow-2xl"><div className="mb-8 flex items-center justify-between"><h2 className="text-sm font-bold uppercase tracking-[.14em]">Bộ lọc</h2><button onClick={() => setDrawer(false)} className="grid size-10 place-items-center border border-white/10"><X size={18} /></button></div>{filters}<button onClick={() => setDrawer(false)} className="mt-8 min-h-12 w-full bg-[#f8f5ee] text-sm font-bold text-black">Xem {products.length} sản phẩm</button></aside></div>}</div>;
}

type FilterProps = { category:string; setCategory:(v:string)=>void; maxPrice:number; setMaxPrice:(v:number)=>void; color:string; setColor:(v:string)=>void; size:string; setSize:(v:string)=>void; status:string; setStatus:(v:string)=>void; colors:string[] };
function FilterFields(p: FilterProps) { return <div className="space-y-7 text-sm"><Filter title="Danh mục"><div className="space-y-2">{["Tất cả", ...rentalCategories].map((value) => <Choice key={value} active={p.category===value} onClick={()=>p.setCategory(value)}>{value}</Choice>)}</div></Filter><Filter title="Khoảng giá"><input aria-label="Giá tối đa" type="range" min={300000} max={700000} step={50000} value={p.maxPrice} onChange={(e)=>p.setMaxPrice(Number(e.target.value))} className="w-full accent-[#d8b766]" /><p className="mt-2 text-xs text-white/45">Tối đa {p.maxPrice.toLocaleString("vi-VN")}đ</p></Filter><Filter title="Màu sắc"><select value={p.color} onChange={(e)=>p.setColor(e.target.value)} className="rental-select"><option>Tất cả</option>{p.colors.map((v)=><option key={v}>{v}</option>)}</select></Filter><Filter title="Size"><div className="flex flex-wrap gap-2">{["Tất cả",...rentalSizes].map((v)=><button key={v} onClick={()=>p.setSize(v)} className={`min-h-9 min-w-9 border px-2 text-xs ${p.size===v?"border-[#d8b766] text-[#f3d88e]":"border-white/10 text-white/55"}`}>{v}</button>)}</div></Filter><Filter title="Trạng thái"><select value={p.status} onChange={(e)=>p.setStatus(e.target.value)} className="rental-select"><option>Tất cả</option>{Object.entries(rentalStatusMeta).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select></Filter></div> }
function Filter({title,children}:{title:string;children:React.ReactNode}) { return <fieldset className="border-b border-white/10 pb-7"><legend className="mb-4 text-xs font-bold uppercase tracking-[.12em] text-white">{title}</legend>{children}</fieldset> }
function Choice({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}) { return <button onClick={onClick} className={`block w-full py-1 text-left transition ${active?"text-[#f3d88e]":"text-white/55 hover:text-white"}`}>{children}</button> }
