"use client";

import { CheckCircle2, Clock3 } from "lucide-react";
import { useEffect, useState } from "react";
import { formatRentalMoney } from "@/lib/rental/catalog";

type Order={orderCode:string;status:string;depositVnd:number;paidDepositVnd:number;remainingVnd:number};
export function RentalPaymentStatus({orderCode}:{orderCode:string}){const[order,setOrder]=useState<Order|null>(null);const[error,setError]=useState("");useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;const load=async()=>{try{const response=await fetch(`/api/rental/orders/${orderCode}`,{cache:"no-store"});const payload=await response.json() as {order?:Order;error?:string};if(!active)return;if(payload.order){setOrder(payload.order);if(payload.order.status==="pending")timer=setTimeout(load,2500)}else setError(payload.error||"Không tìm thấy đơn.");}catch{if(active)timer=setTimeout(load,3000)}};void load();return()=>{active=false;clearTimeout(timer)}},[orderCode]);const paid=order?.status==="paid";return <div className="mx-auto max-w-xl px-5 py-24 text-center">{paid?<CheckCircle2 className="mx-auto text-emerald-300" size={58}/>:<Clock3 className="mx-auto text-[#f3d88e]" size={54}/>}<p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-white/45">{paid?"Thanh toán thành công":"Đang xác nhận SePay"}</p><h1 className="mt-3 text-3xl font-semibold">{orderCode}</h1>{order&&<div className="mt-8 rounded-lg border border-white/10 bg-white/[.03] p-6 text-left"><Row label="Tiền cọc" value={formatRentalMoney(order.depositVnd)}/><Row label="Đã thanh toán" value={formatRentalMoney(order.paidDepositVnd)}/><Row label="Còn lại" value={formatRentalMoney(order.remainingVnd)}/></div>}<p className="mt-8 text-sm leading-7 text-white/55">Vui lòng chụp lại mã đơn và mang CCCD tới Studio để nhận trang phục.</p>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}</div>}
function Row({label,value}:{label:string;value:string}){return <div className="mt-3 flex justify-between gap-5 text-sm first:mt-0"><span className="text-white/45">{label}</span><b>{value}</b></div>}
