"use client";

import { Bold, Code2, ImagePlus, Italic, Link2, List, ListOrdered, Loader2, Newspaper, Strikethrough, Underline, Upload, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { ReactNode } from "react";

type Post = { id: string; title: string; slug: string; excerpt: string | null; cover_image_url: string | null; keywords: string | null; published: boolean; created_at: string };
type Form = { title: string; excerpt: string; keywords: string; coverImageUrl: string; content: string; published: boolean };
type ImageSize = "full" | "medium" | "small";
const initialForm: Form = { title: "", excerpt: "", keywords: "", coverImageUrl: "", content: "<p>Bắt đầu viết câu chuyện của bạn tại đây...</p>", published: true };
const colors = ["#18181b", "#dc2626", "#ea580c", "#ca8a04", "#16a34a", "#0891b2", "#2563eb", "#7c3aed", "#db2777"];

async function compactImage(file: File, maxWidth: number) {
  const source = await createImageBitmap(file); const ratio = Math.min(1, maxWidth / source.width);
  const canvas = document.createElement("canvas"); canvas.width = Math.round(source.width * ratio); canvas.height = Math.round(source.height * ratio);
  canvas.getContext("2d")?.drawImage(source, 0, 0, canvas.width, canvas.height); source.close();
  return await new Promise<string>((resolve) => canvas.toBlob(blob => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(blob || file); }, "image/webp", 0.78));
}

export function StudioNewsManager() {
  const [posts, setPosts] = useState<Post[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [tab, setTab] = useState<"write" | "code">("write"); const [form, setForm] = useState<Form>(initialForm);
  const [linkModal, setLinkModal] = useState(false); const [linkUrl, setLinkUrl] = useState(""); const [imageModal, setImageModal] = useState(false); const [imageFile, setImageFile] = useState<File | null>(null); const [alt, setAlt] = useState(""); const [caption, setCaption] = useState(""); const [imageSize, setImageSize] = useState<ImageSize>("full"); const [processingImage, setProcessingImage] = useState(false);
  const editor = useRef<HTMLDivElement>(null); const coverInput = useRef<HTMLInputElement>(null); const articleImageInput = useRef<HTMLInputElement>(null); const range = useRef<Range | null>(null);
  useEffect(() => { fetch("/api/admin/posts").then(async r => ({ r, d: await r.json() as { posts?: Post[]; error?: string } })).then(({ r, d }) => { if (!r.ok) setError(d.error || "Không tải được bài viết."); else setPosts(d.posts || []); }).catch(() => setError("Không tải được bài viết.")).finally(() => setLoading(false)); }, []);
  function updateContent(html: string) { setForm(current => ({ ...current, content: html })); }
  function rememberSelection() { const selection = window.getSelection(); if (selection?.rangeCount) range.current = selection.getRangeAt(0).cloneRange(); }
  function restoreSelection() { if (!range.current) return; const selection = window.getSelection(); selection?.removeAllRanges(); selection?.addRange(range.current); }
  function command(name: string, value?: string) { editor.current?.focus(); restoreSelection(); document.execCommand(name, false, value); updateContent(editor.current?.innerHTML || form.content); rememberSelection(); }
  async function uploadCover(file: File) { try { setProcessingImage(true); setForm(current => ({ ...current, coverImageUrl: "" })); const src = await compactImage(file, 1200); setForm(current => ({ ...current, coverImageUrl: src })); } finally { setProcessingImage(false); } }
  async function insertImage() { if (!imageFile) return; setProcessingImage(true); try { const src = await compactImage(imageFile, 1600); editor.current?.focus(); restoreSelection(); const selection = window.getSelection(); const insertRange = selection?.rangeCount ? selection.getRangeAt(0) : null; const figure = document.createElement("figure"); figure.className = `news-image news-image--${imageSize}`; const image = document.createElement("img"); image.src = src; image.alt = alt.trim(); image.loading = "lazy"; figure.append(image); if (caption.trim()) { const figcaption = document.createElement("figcaption"); figcaption.textContent = caption.trim(); figure.append(figcaption); } if (insertRange) { insertRange.deleteContents(); insertRange.insertNode(figure); insertRange.setStartAfter(figure); insertRange.collapse(true); selection?.removeAllRanges(); selection?.addRange(insertRange); } else editor.current?.append(figure); updateContent(editor.current?.innerHTML || form.content); setImageModal(false); setImageFile(null); setAlt(""); setCaption(""); setImageSize("full"); } finally { setProcessingImage(false); } }
  function confirmLink() { if (!linkUrl.trim()) return; command("createLink", linkUrl.trim()); setLinkUrl(""); setLinkModal(false); }
  async function save() { setSaving(true); setError(""); try { const r = await fetch("/api/admin/posts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json() as { post?: Post; error?: string }; if (!r.ok || !d.post) throw new Error(d.error || "Không tạo được bài viết."); setPosts(current => [d.post!, ...current]); setForm(initialForm); setOpen(false); } catch (e) { setError(e instanceof Error ? e.message : "Không tạo được bài viết."); } finally { setSaving(false); } }
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#c99a5e]">Nội dung website</p><h1 className="mt-2 text-3xl font-extrabold">Tin tức</h1><p className="mt-2 text-sm text-zinc-600">Soạn bài đầy đủ như WordPress, tối ưu cho trang đọc, SEO và khi chia sẻ mạng xã hội.</p></div><button onClick={() => setOpen(v => !v)} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-zinc-950 px-4 text-sm font-semibold text-white">{open ? "Đóng soạn thảo" : "Thêm bài viết"}</button></div>
    {open && <section className="rounded-xl border border-zinc-200 bg-white shadow-sm"><div className="border-b border-zinc-200 p-5"><div className="grid gap-4 lg:grid-cols-[1fr_300px]"><div className="space-y-4"><input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="Tiêu đề bài viết" className="min-h-12 w-full rounded-md border border-zinc-300 px-4 text-xl font-bold outline-none focus:border-zinc-950" /><textarea value={form.excerpt} maxLength={160} onChange={e => setForm({ ...form, excerpt: e.target.value })} placeholder="Mô tả ngắn — dùng cho kết quả tìm kiếm và OG meta tag" className="min-h-20 w-full rounded-md border border-zinc-300 p-3 text-sm outline-none focus:border-zinc-950" /><p className="-mt-2 text-right text-xs text-zinc-500">{form.excerpt.length}/160 ký tự</p></div><div className="space-y-4"><label className="block text-sm font-semibold">Từ khoá SEO<input value={form.keywords} onChange={e => setForm({ ...form, keywords: e.target.value })} placeholder="chụp ảnh, studio, profile" className="mt-2 min-h-11 w-full rounded-md border border-zinc-300 px-3 text-sm font-normal" /><span className="mt-1 block text-xs font-normal text-zinc-500">Ngăn cách bằng dấu phẩy. Từ khoá được đưa vào metadata SEO của bài.</span></label><input ref={coverInput} type="file" accept="image/*" className="hidden" onChange={e => { const file = e.target.files?.[0]; if (file) void uploadCover(file); e.currentTarget.value = ""; }} /><div className="rounded-lg border border-dashed border-zinc-300 p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold">Ảnh bìa bài viết</p><p className="mt-1 text-xs text-zinc-500">Tự nén WebP, tối đa 1200 px — dùng cho OG và danh sách tin.</p></div><button type="button" onClick={() => coverInput.current?.click()} className="inline-flex shrink-0 items-center gap-2 rounded-md border border-zinc-300 px-3 py-2 text-xs font-bold hover:bg-zinc-50"><Upload size={15}/>Tải ảnh</button></div>{form.coverImageUrl && <div className="relative mt-3 aspect-video overflow-hidden rounded-md bg-zinc-100"><img src={form.coverImageUrl} alt="Xem trước ảnh bìa" className="size-full object-cover" /><button type="button" onClick={() => setForm({ ...form, coverImageUrl: "" })} className="absolute right-2 top-2 grid size-8 place-items-center rounded-full bg-black/70 text-white" aria-label="Xóa ảnh bìa"><X size={16}/></button></div>}{processingImage && <p className="mt-2 text-xs text-zinc-500">Đang nén ảnh…</p>}</div></div></div></div>
      <div className="flex border-b border-zinc-200 px-5"><button onClick={() => setTab("write")} className={`border-b-2 px-4 py-3 text-sm font-bold ${tab === "write" ? "border-zinc-950 text-zinc-950" : "border-transparent text-zinc-500"}`}>Trình soạn thảo</button><button onClick={() => setTab("code")} className={`inline-flex items-center gap-2 border-b-2 px-4 py-3 text-sm font-bold ${tab === "code" ? "border-zinc-950 text-zinc-950" : "border-transparent text-zinc-500"}`}><Code2 size={16}/>Code UI (HTML)</button></div>
      {tab === "write" ? <div className="p-5"><div className="news-toolbar sticky top-2 z-20 flex flex-wrap items-center gap-1 rounded-md border border-zinc-300 bg-zinc-50/95 p-2 shadow-sm backdrop-blur"><Tool label="Đậm" icon={<Bold size={16}/>} onClick={() => command("bold")} /><Tool label="Nghiêng" icon={<Italic size={16}/>} onClick={() => command("italic")} /><Tool label="Gạch chân" icon={<Underline size={16}/>} onClick={() => command("underline")} /><Tool label="Gạch xoá" icon={<Strikethrough size={16}/>} onClick={() => command("strikeThrough")} /><select aria-label="Phông chữ" defaultValue="inherit" onMouseDown={rememberSelection} onChange={e => command("fontName", e.target.value)} className="h-9 rounded border border-zinc-200 bg-white px-2 text-sm"><option value="inherit">Google Sans</option><option value="Arial">Arial</option><option value="Georgia">Georgia</option><option value="Courier New">Courier New</option></select><div className="flex items-center gap-1 border-x border-zinc-200 px-2">{colors.map(color => <button key={color} type="button" title={`Màu ${color}`} onMouseDown={e => { e.preventDefault(); rememberSelection(); }} onClick={() => command("foreColor", color)} className="size-5 rounded-full border border-black/10" style={{ backgroundColor: color }} />)}</div><Tool label="Danh sách chấm" icon={<List size={16}/>} onClick={() => command("insertUnorderedList")} /><Tool label="Danh sách số" icon={<ListOrdered size={16}/>} onClick={() => command("insertOrderedList")} /><Tool label="Tạo liên kết" icon={<Link2 size={16}/>} onClick={() => { rememberSelection(); setLinkModal(true); }} /><Tool label="Chèn ảnh" icon={<ImagePlus size={16}/>} onClick={() => { rememberSelection(); articleImageInput.current?.click(); }} /><input ref={articleImageInput} type="file" accept="image/*" className="hidden" onChange={e => { const file = e.target.files?.[0]; if (file) { setImageFile(file); setImageModal(true); } e.currentTarget.value = ""; }} /></div><div ref={editor} contentEditable suppressContentEditableWarning onInput={e => { updateContent(e.currentTarget.innerHTML); rememberSelection(); }} onKeyUp={rememberSelection} onMouseUp={rememberSelection} dangerouslySetInnerHTML={{ __html: form.content }} className="news-editor min-h-96 rounded-b-md border border-t-0 border-zinc-300 p-6 text-[16px] leading-8 text-zinc-800 outline-none" /></div> : <div className="p-5"><textarea value={form.content} onChange={e => updateContent(e.target.value)} spellCheck={false} className="min-h-96 w-full rounded-md border border-zinc-300 bg-zinc-950 p-5 font-mono text-sm leading-7 text-emerald-200 outline-none" /><p className="mt-3 text-xs leading-5 text-zinc-500">Dán HTML để tạo bố cục riêng. Chỉ dùng nội dung bạn tin cậy; HTML sẽ được hiển thị trực tiếp trên trang bài viết.</p></div>}
      <div className="flex flex-wrap items-center justify-between gap-4 border-t border-zinc-200 p-5"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.published} onChange={e => setForm({ ...form, published: e.target.checked })} />Xuất bản ngay</label><button disabled={saving || !form.title.trim()} onClick={save} className="rounded-md bg-[#c99a5e] px-5 py-2.5 text-sm font-bold text-zinc-950 disabled:opacity-60">{saving && <Loader2 size={15} className="mr-2 inline animate-spin" />}Lưu bài viết</button></div></section>}
    {linkModal && <Modal title="Tạo liên kết" onClose={() => setLinkModal(false)}><label className="block text-sm font-semibold">Đường dẫn<input autoFocus value={linkUrl} onChange={e => setLinkUrl(e.target.value)} placeholder="https://..." className="mt-2 min-h-11 w-full rounded-md border border-zinc-300 px-3 font-normal" /></label><button onClick={confirmLink} className="mt-5 rounded-md bg-zinc-950 px-4 py-2 text-sm font-bold text-white">Xác nhận liên kết</button></Modal>}
    {imageModal && <Modal title="Thông tin ảnh" onClose={() => setImageModal(false)}><p className="text-sm text-zinc-500">Ảnh sẽ được nén sang WebP trước khi chèn để giảm dung lượng.</p><label className="mt-4 block text-sm font-semibold">Alt ảnh (SEO)<input autoFocus value={alt} onChange={e => setAlt(e.target.value)} placeholder="Mô tả ngắn, rõ nội dung ảnh" className="mt-2 min-h-11 w-full rounded-md border border-zinc-300 px-3 font-normal" /></label><label className="mt-4 block text-sm font-semibold">Mô tả / chú thích ảnh<textarea value={caption} onChange={e => setCaption(e.target.value)} placeholder="Hiển thị bên dưới ảnh" className="mt-2 min-h-20 w-full rounded-md border border-zinc-300 p-3 font-normal" /></label><fieldset className="mt-4"><legend className="text-sm font-semibold">Kích thước hiển thị</legend><div className="mt-2 flex gap-2">{(["full", "medium", "small"] as ImageSize[]).map(size => <button key={size} onClick={() => setImageSize(size)} className={`rounded-md border px-3 py-2 text-sm font-semibold ${imageSize === size ? "border-zinc-950 bg-zinc-950 text-white" : "border-zinc-300"}`}>{size === "full" ? "Full" : size === "medium" ? "Medium" : "Small"}</button>)}</div></fieldset><button disabled={processingImage} onClick={() => void insertImage()} className="mt-5 rounded-md bg-zinc-950 px-4 py-2 text-sm font-bold text-white disabled:opacity-60">{processingImage ? "Đang nén ảnh..." : "Chèn ảnh"}</button></Modal>}
    {error && <p className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="overflow-hidden rounded-lg border border-zinc-200 bg-white shadow-sm"><div className="border-b border-zinc-200 p-5 font-bold">Tất cả bài viết</div>{loading ? <p className="p-5 text-sm text-zinc-500">Đang tải…</p> : posts.length === 0 ? <p className="p-8 text-center text-sm text-zinc-500"><Newspaper className="mx-auto mb-3" />Chưa có bài viết nào.</p> : <div className="divide-y divide-zinc-100">{posts.map(post => <div key={post.id} className="flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-4">{post.cover_image_url && <img src={post.cover_image_url} alt="" className="size-12 rounded object-cover" />}<div><p className="font-bold text-zinc-950">{post.title}</p><p className="mt-1 text-sm text-zinc-500">/{post.slug}</p></div></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${post.published ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{post.published ? "Đã xuất bản" : "Bản nháp"}</span></div>)}</div>}</section></div>;
}
function Tool({ label, icon, onClick }: { label: string; icon: ReactNode; onClick: () => void }) { return <button type="button" title={label} onMouseDown={e => e.preventDefault()} onClick={onClick} className="grid size-9 place-items-center rounded hover:bg-zinc-200">{icon}</button>; }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><section className="w-full max-w-lg rounded-xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><button onClick={onClose} className="grid size-8 place-items-center rounded hover:bg-zinc-100" aria-label="Đóng"><X size={18}/></button></div>{children}</section></div>; }
