"use client";

import { Bold, Code2, ImagePlus, Italic, Link2, List, Loader2, Newspaper, Strikethrough, Underline } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { ReactNode } from "react";

type Post = { id: string; title: string; slug: string; excerpt: string | null; cover_image_url: string | null; keywords: string | null; published: boolean; created_at: string };
type Form = { title: string; excerpt: string; keywords: string; coverImageUrl: string; content: string; published: boolean };
const initialForm: Form = { title: "", excerpt: "", keywords: "", coverImageUrl: "", content: "<p>Bắt đầu viết câu chuyện của bạn tại đây...</p>", published: true };

export function StudioNewsManager() {
  const [posts, setPosts] = useState<Post[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [tab, setTab] = useState<"write" | "code">("write"); const [form, setForm] = useState<Form>(initialForm); const editor = useRef<HTMLDivElement>(null); const imageInput = useRef<HTMLInputElement>(null);
  useEffect(() => { fetch("/api/admin/posts").then(async r => ({ r, d: await r.json() as { posts?: Post[]; error?: string } })).then(({ r, d }) => { if (!r.ok) setError(d.error || "Không tải được bài viết."); else setPosts(d.posts || []); }).catch(() => setError("Không tải được bài viết.")).finally(() => setLoading(false)); }, []);
  function updateContent(html: string) { setForm(current => ({ ...current, content: html })); }
  function command(name: string, value?: string) { editor.current?.focus(); document.execCommand(name, false, value); updateContent(editor.current?.innerHTML || form.content); }
  function addLink() { const url = window.prompt("Dán đường dẫn liên kết"); if (url) command("createLink", url); }
  function addImage(file: File) { const reader = new FileReader(); reader.onload = () => { const src = String(reader.result); command("insertImage", src); }; reader.readAsDataURL(file); }
  async function save() { setSaving(true); setError(""); try { const r = await fetch("/api/admin/posts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json() as { post?: Post; error?: string }; if (!r.ok || !d.post) throw new Error(d.error || "Không tạo được bài viết."); setPosts(current => [d.post!, ...current]); setForm(initialForm); setOpen(false); } catch (e) { setError(e instanceof Error ? e.message : "Không tạo được bài viết."); } finally { setSaving(false); } }
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#c99a5e]">Nội dung website</p><h1 className="mt-2 text-3xl font-extrabold">Tin tức</h1><p className="mt-2 text-sm text-zinc-600">Soạn bài đầy đủ như WordPress, tối ưu cho trang đọc và khi chia sẻ mạng xã hội.</p></div><button onClick={() => setOpen(v => !v)} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-zinc-950 px-4 text-sm font-semibold text-white">{open ? "Đóng soạn thảo" : "Thêm bài viết"}</button></div>
    {open && <section className="rounded-xl border border-zinc-200 bg-white shadow-sm"><div className="border-b border-zinc-200 p-5"><div className="grid gap-4 lg:grid-cols-[1fr_280px]"><div className="space-y-4"><input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="Tiêu đề bài viết" className="min-h-12 w-full rounded-md border border-zinc-300 px-4 text-xl font-bold outline-none focus:border-zinc-950" /><textarea value={form.excerpt} maxLength={160} onChange={e => setForm({ ...form, excerpt: e.target.value })} placeholder="Mô tả ngắn — dùng cho phần giới thiệu và OG meta tag" className="min-h-20 w-full rounded-md border border-zinc-300 p-3 text-sm outline-none focus:border-zinc-950" /><p className="-mt-2 text-right text-xs text-zinc-500">{form.excerpt.length}/160 ký tự</p></div><div className="space-y-4"><input value={form.keywords} onChange={e => setForm({ ...form, keywords: e.target.value })} placeholder="Từ khoá: chụp ảnh, studio..." className="min-h-11 w-full rounded-md border border-zinc-300 px-3 text-sm" /><input value={form.coverImageUrl} onChange={e => setForm({ ...form, coverImageUrl: e.target.value })} placeholder="Link ảnh bìa (1200 × 630)" className="min-h-11 w-full rounded-md border border-zinc-300 px-3 text-sm" /><p className="text-xs leading-5 text-zinc-500">Ảnh bìa dùng cho danh sách tin và khi chia sẻ link bài viết.</p></div></div></div>
      <div className="flex border-b border-zinc-200 px-5"><button onClick={() => setTab("write")} className={`border-b-2 px-4 py-3 text-sm font-bold ${tab === "write" ? "border-zinc-950 text-zinc-950" : "border-transparent text-zinc-500"}`}>Trình soạn thảo</button><button onClick={() => setTab("code")} className={`inline-flex items-center gap-2 border-b-2 px-4 py-3 text-sm font-bold ${tab === "code" ? "border-zinc-950 text-zinc-950" : "border-transparent text-zinc-500"}`}><Code2 size={16}/>Code UI (HTML)</button></div>
      {tab === "write" ? <div className="p-5"><div className="flex flex-wrap items-center gap-1 rounded-t-md border border-zinc-300 bg-zinc-50 p-2"><Tool label="Đậm" icon={<Bold size={16}/>} onClick={() => command("bold")} /><Tool label="Nghiêng" icon={<Italic size={16}/>} onClick={() => command("italic")} /><Tool label="Gạch chân" icon={<Underline size={16}/>} onClick={() => command("underline")} /><Tool label="Gạch xoá" icon={<Strikethrough size={16}/>} onClick={() => command("strikeThrough")} /><select aria-label="Màu chữ" onChange={e => command("foreColor", e.target.value)} className="h-9 rounded border border-zinc-200 bg-white px-2 text-sm"><option value="#18181b">Màu chữ</option><option value="#dc2626">Đỏ</option><option value="#2563eb">Xanh</option><option value="#16a34a">Lục</option></select><Tool label="Danh sách" icon={<List size={16}/>} onClick={() => command("insertUnorderedList")} /><Tool label="Chèn liên kết" icon={<Link2 size={16}/>} onClick={addLink} /><Tool label="Chèn ảnh" icon={<ImagePlus size={16}/>} onClick={() => imageInput.current?.click()} /><input ref={imageInput} type="file" accept="image/*" className="hidden" onChange={e => e.target.files?.[0] && addImage(e.target.files[0])}/></div><div ref={editor} contentEditable suppressContentEditableWarning onInput={e => updateContent(e.currentTarget.innerHTML)} dangerouslySetInnerHTML={{ __html: form.content }} className="news-editor min-h-96 rounded-b-md border border-t-0 border-zinc-300 p-6 text-[16px] leading-8 text-zinc-800 outline-none" /></div> : <div className="p-5"><textarea value={form.content} onChange={e => updateContent(e.target.value)} spellCheck={false} className="min-h-96 w-full rounded-md border border-zinc-300 bg-zinc-950 p-5 font-mono text-sm leading-7 text-emerald-200 outline-none" /><p className="mt-3 text-xs leading-5 text-zinc-500">Dán HTML để tạo bố cục riêng. Chỉ dùng nội dung bạn tin cậy; HTML sẽ được hiển thị trực tiếp trên trang bài viết.</p></div>}
      <div className="flex flex-wrap items-center justify-between gap-4 border-t border-zinc-200 p-5"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.published} onChange={e => setForm({ ...form, published: e.target.checked })} />Xuất bản ngay</label><button disabled={saving || !form.title.trim()} onClick={save} className="rounded-md bg-[#c99a5e] px-5 py-2.5 text-sm font-bold text-zinc-950 disabled:opacity-60">{saving && <Loader2 size={15} className="mr-2 inline animate-spin" />}Lưu bài viết</button></div></section>}
    {error && <p className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="overflow-hidden rounded-lg border border-zinc-200 bg-white shadow-sm"><div className="border-b border-zinc-200 p-5 font-bold">Tất cả bài viết</div>{loading ? <p className="p-5 text-sm text-zinc-500">Đang tải…</p> : posts.length === 0 ? <p className="p-8 text-center text-sm text-zinc-500"><Newspaper className="mx-auto mb-3" />Chưa có bài viết nào.</p> : <div className="divide-y divide-zinc-100">{posts.map(post => <div key={post.id} className="flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-4">{post.cover_image_url && <img src={post.cover_image_url} alt="" className="size-12 rounded object-cover" />}<div><p className="font-bold text-zinc-950">{post.title}</p><p className="mt-1 text-sm text-zinc-500">/{post.slug}</p></div></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${post.published ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{post.published ? "Đã xuất bản" : "Bản nháp"}</span></div>)}</div>}</section></div>;
}
function Tool({ label, icon, onClick }: { label: string; icon: ReactNode; onClick: () => void }) { return <button type="button" title={label} onMouseDown={e => e.preventDefault()} onClick={onClick} className="grid size-9 place-items-center rounded hover:bg-zinc-200">{icon}</button>; }
