"use client";

import { FilePlus2, Loader2, Newspaper } from "lucide-react";
import { useEffect, useState } from "react";

type Post = { id: string; title: string; slug: string; excerpt: string | null; published: boolean; created_at: string };

export function StudioNewsManager() {
  const [posts, setPosts] = useState<Post[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ title: "", excerpt: "", content: "", published: true });
  useEffect(() => { fetch("/api/admin/posts").then(async r => ({ r, d: await r.json() as { posts?: Post[]; error?: string } })).then(({ r, d }) => { if (!r.ok) setError(d.error || "Không tải được bài viết."); else setPosts(d.posts || []); }).catch(() => setError("Không tải được bài viết.")).finally(() => setLoading(false)); }, []);
  async function save() { setSaving(true); setError(""); try { const r = await fetch("/api/admin/posts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json() as { post?: Post; error?: string }; if (!r.ok || !d.post) throw new Error(d.error || "Không tạo được bài viết."); setPosts(current => [d.post!, ...current]); setForm({ title: "", excerpt: "", content: "", published: true }); setOpen(false); } catch (e) { setError(e instanceof Error ? e.message : "Không tạo được bài viết."); } finally { setSaving(false); } }
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#c99a5e]">Nội dung website</p><h1 className="mt-2 text-3xl font-extrabold">Tin tức</h1><p className="mt-2 text-sm text-zinc-600">Quản lý các bài viết xuất bản trên website studio.</p></div><button onClick={() => setOpen(v => !v)} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-zinc-950 px-4 text-sm font-semibold text-white"><FilePlus2 size={16} />Thêm bài viết</button></div>{open && <section className="rounded-lg border border-zinc-200 bg-white p-5 shadow-sm"><div className="grid gap-4"><input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="Tiêu đề bài viết" className="min-h-11 rounded-md border border-zinc-300 px-3 text-lg font-bold" /><textarea value={form.excerpt} onChange={e => setForm({ ...form, excerpt: e.target.value })} placeholder="Mô tả ngắn" className="min-h-20 rounded-md border border-zinc-300 p-3" /><textarea value={form.content} onChange={e => setForm({ ...form, content: e.target.value })} placeholder="Nội dung bài viết" className="min-h-52 rounded-md border border-zinc-300 p-3" /><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.published} onChange={e => setForm({ ...form, published: e.target.checked })} />Xuất bản ngay</label><button disabled={saving} onClick={save} className="w-fit rounded-md bg-[#c99a5e] px-5 py-2.5 text-sm font-bold text-zinc-950 disabled:opacity-60">{saving && <Loader2 size={15} className="mr-2 inline animate-spin" />}Lưu bài viết</button></div></section>}{error && <p className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="overflow-hidden rounded-lg border border-zinc-200 bg-white shadow-sm"><div className="border-b border-zinc-200 p-5 font-bold">Tất cả bài viết</div>{loading ? <p className="p-5 text-sm text-zinc-500">Đang tải…</p> : posts.length === 0 ? <p className="p-8 text-center text-sm text-zinc-500"><Newspaper className="mx-auto mb-3" />Chưa có bài viết nào.</p> : <div className="divide-y divide-zinc-100">{posts.map(post => <div key={post.id} className="flex items-center justify-between gap-4 p-5"><div><p className="font-bold text-zinc-950">{post.title}</p><p className="mt-1 text-sm text-zinc-500">/{post.slug}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${post.published ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{post.published ? "Đã xuất bản" : "Bản nháp"}</span></div>)}</div>}</section></div>;
}
