"use client";

import { Plus, Save, Trash2 } from "lucide-react";
import { useState } from "react";

type Item = { title: string; subtitle: string; description: string; image: string; price: string; features: string };
type Content = { hero: { title: string; description: string; image: string; cta: string }; about: { title: string; description: string; image: string }; services: Item[]; pricing: Item[]; gallery: Item[] };
const emptyItem = (): Item => ({ title: "", subtitle: "", description: "", image: "", price: "", features: "" });
const initial: Content = { hero: { title: "", description: "", image: "", cta: "Đặt lịch tư vấn" }, about: { title: "", description: "", image: "" }, services: [emptyItem(), emptyItem(), emptyItem()], pricing: [emptyItem(), emptyItem(), emptyItem()], gallery: [emptyItem(), emptyItem(), emptyItem()] };

export function ThemeContentEditor({ saved }: { saved?: Partial<Content> }) {
  const [content, setContent] = useState<Content>({ ...initial, ...saved, hero: { ...initial.hero, ...saved?.hero }, about: { ...initial.about, ...saved?.about }, services: saved?.services?.length ? saved.services : initial.services, pricing: saved?.pricing?.length ? saved.pricing : initial.pricing, gallery: saved?.gallery?.length ? saved.gallery : initial.gallery });
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const field = (group: "hero" | "about", key: string, label: string, textarea = false) => <label className="block text-sm font-semibold text-zinc-800">{label}{textarea ? <textarea value={(content[group] as any)[key]} onChange={e => setContent(c => ({ ...c, [group]: { ...c[group], [key]: e.target.value } }))} className="mt-2 min-h-20 w-full rounded-md border border-zinc-300 p-3 font-normal" /> : <input value={(content[group] as any)[key]} onChange={e => setContent(c => ({ ...c, [group]: { ...c[group], [key]: e.target.value } }))} className="mt-2 min-h-11 w-full rounded-md border border-zinc-300 px-3 font-normal" />}</label>;
  function update(type: "services" | "pricing" | "gallery", index: number, key: keyof Item, value: string) { setContent(c => ({ ...c, [type]: c[type].map((item, i) => i === index ? { ...item, [key]: value } : item) })); }
  function add(type: "services" | "pricing" | "gallery") { setContent(c => ({ ...c, [type]: [...c[type], emptyItem()] })); }
  function remove(type: "services" | "pricing" | "gallery", index: number) { setContent(c => ({ ...c, [type]: c[type].filter((_, i) => i !== index) })); }
  async function save() { setSaving(true); setMessage(""); try { const response = await fetch("/api/admin/studio-settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ settings: { site_content: content } }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Không thể lưu nội dung."); setMessage("Đã đồng bộ nội dung với theme website."); } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể lưu nội dung."); } finally { setSaving(false); } }
  const collection = (type: "services" | "pricing" | "gallery", title: string, hint: string) => <section className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold">{title}</h2><p className="mt-1 text-sm text-zinc-500">{hint}</p></div><button type="button" onClick={() => add(type)} className="inline-flex items-center gap-2 rounded-md border border-zinc-300 px-3 py-2 text-sm font-bold"><Plus size={15}/>Thêm</button></div><div className="mt-5 space-y-4">{content[type].map((item, index) => <div key={index} className="relative grid gap-3 rounded-lg border border-zinc-200 bg-zinc-50 p-4 md:grid-cols-2"><button type="button" onClick={() => remove(type, index)} className="absolute right-2 top-2 text-zinc-400 hover:text-red-600" aria-label="Xóa"><Trash2 size={16}/></button><label className="text-sm font-semibold">Tên / tiêu đề<input value={item.title} onChange={e => update(type, index, "title", e.target.value)} className="mt-1 min-h-10 w-full rounded border border-zinc-300 bg-white px-3 font-normal" /></label><label className="text-sm font-semibold">Nhãn phụ / danh mục<input value={item.subtitle} onChange={e => update(type, index, "subtitle", e.target.value)} className="mt-1 min-h-10 w-full rounded border border-zinc-300 bg-white px-3 font-normal" /></label><label className="text-sm font-semibold md:col-span-2">Mô tả<textarea value={item.description} onChange={e => update(type, index, "description", e.target.value)} className="mt-1 min-h-18 w-full rounded border border-zinc-300 bg-white p-3 font-normal" /></label><label className="text-sm font-semibold">Giá<input value={item.price} onChange={e => update(type, index, "price", e.target.value)} placeholder="1.500.000đ" className="mt-1 min-h-10 w-full rounded border border-zinc-300 bg-white px-3 font-normal" /></label><label className="text-sm font-semibold">Ảnh (URL)<input value={item.image} onChange={e => update(type, index, "image", e.target.value)} className="mt-1 min-h-10 w-full rounded border border-zinc-300 bg-white px-3 font-normal" /></label><label className="text-sm font-semibold md:col-span-2">Điểm nổi bật (cách nhau dấu phẩy)<input value={item.features} onChange={e => update(type, index, "features", e.target.value)} className="mt-1 min-h-10 w-full rounded border border-zinc-300 bg-white px-3 font-normal" /></label></div>)}</div></section>;
  return <div className="mt-5 space-y-5"><section className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Nội dung trang chủ</h2><p className="mt-1 text-sm text-zinc-500">Các dữ liệu này thay thế câu từ và ảnh mẫu trong theme đã chọn.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{field("hero", "title", "Tiêu đề Hero")}{field("hero", "cta", "Nhãn nút hành động")}{field("hero", "description", "Mô tả Hero", true)}{field("hero", "image", "Ảnh Hero (URL)")}{field("about", "title", "Tiêu đề giới thiệu")}{field("about", "image", "Ảnh giới thiệu (URL)")}{field("about", "description", "Nội dung giới thiệu", true)}</div></section>{collection("services", "Dịch vụ", "Thêm, xóa và thay đổi dịch vụ hiển thị trên website.")}{collection("pricing", "Bảng giá", "Quản lý các gói, giá và quyền lợi.")}{collection("gallery", "Album / Portfolio", "Quản lý nội dung các album nổi bật.")}<div className="flex items-center gap-3"><button type="button" disabled={saving} onClick={save} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-zinc-950 px-5 text-sm font-bold text-white disabled:opacity-60"><Save size={16}/>{saving ? "Đang lưu..." : "Lưu nội dung website"}</button>{message && <p className="text-sm font-semibold text-emerald-700">{message}</p>}</div></div>;
}
