var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/payments/sepay/checkout/route.js")
R.c("server/chunks/[root-of-the-server]__0nj99x8._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/[root-of-the-server]__1er92z0._.js")
R.c("server/chunks/node_modules_0t08xuk._.js")
R.c("server/chunks/src_lib_supabase_admin_ts_0cfteh4._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/_next-internal_server_app_api_payments_sepay_checkout_route_actions_0jfp531.js")
R.m(65867)
module.exports=R.m(65867).exports
