var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/dang-nhap/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__005v017._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_007lr8u.js")
R.c("server/chunks/ssr/[root-of-the-server]__186sgu7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1map00z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06agv4m._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_0-a_o6l._.js")
R.c("server/chunks/ssr/_0j3skur._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_dang-nhap_page_actions_1te9wwy.js")
R.m(11071)
module.exports=R.m(11071).exports
