var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(portal)/cong-khach-hang/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1i_4hm0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ag39cp.js")
R.c("server/chunks/ssr/[root-of-the-server]__186sgu7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1map00z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06agv4m._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_209rgto._.js")
R.c("server/chunks/ssr/_0j3skur._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(portal)_cong-khach-hang_page_actions_1yde87t.js")
R.m(61363)
module.exports=R.m(61363).exports
