// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[customerSlug]" | "/[customerSlug]/done" | "/admin-studio" | "/ai-concept" | "/bang-gia" | "/chinh-sach-bao-mat" | "/dang-ky" | "/dang-nhap" | "/dich-vu" | "/dieu-khoan-dich-vu" | "/studio-site/[studioSlug]" | "/studio-site/[studioSlug]/quan-tri" | "/studio-site/[studioSlug]/tin-tuc" | "/studio-site/[studioSlug]/tin-tuc/[postSlug]" | "/thanh-toan/[orderId]" | "/tin-tuc" | "/tin-tuc/[slug]"
type AppRouteHandlerRoutes = "/api/account/top-up" | "/api/admin/customer-galleries" | "/api/admin/customer-galleries/[slug]" | "/api/admin/gmail/test" | "/api/admin/payment-settings" | "/api/admin/posts" | "/api/ai/generate" | "/api/auth/resolve-email" | "/api/customer-galleries/[slug]/download" | "/api/customer-galleries/[slug]/payment" | "/api/customer-galleries/[slug]/sync" | "/api/customer-galleries/photos/[photoId]" | "/api/customer-galleries/photos/[photoId]/download" | "/api/google-drive/callback" | "/api/google-drive/connect" | "/api/google-drive/status" | "/api/google-drive/sync" | "/api/license/activate" | "/api/license/verify" | "/api/payments/sepay/checkout" | "/api/payments/sepay/ipn" | "/api/payments/vietqr" | "/api/registration/availability" | "/api/tlora/albums" | "/api/tlora/edit-requests" | "/api/tlora/edited-uploads" | "/api/tlora/health" | "/api/tlora/photos" | "/api/tlora/upload" | "/api/vietqr/banks"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[customerSlug]": { "customerSlug": string; }
  "/[customerSlug]/done": { "customerSlug": string; }
  "/admin-studio": {}
  "/ai-concept": {}
  "/api/account/top-up": {}
  "/api/admin/customer-galleries": {}
  "/api/admin/customer-galleries/[slug]": { "slug": string; }
  "/api/admin/gmail/test": {}
  "/api/admin/payment-settings": {}
  "/api/admin/posts": {}
  "/api/ai/generate": {}
  "/api/auth/resolve-email": {}
  "/api/customer-galleries/[slug]/download": { "slug": string; }
  "/api/customer-galleries/[slug]/payment": { "slug": string; }
  "/api/customer-galleries/[slug]/sync": { "slug": string; }
  "/api/customer-galleries/photos/[photoId]": { "photoId": string; }
  "/api/customer-galleries/photos/[photoId]/download": { "photoId": string; }
  "/api/google-drive/callback": {}
  "/api/google-drive/connect": {}
  "/api/google-drive/status": {}
  "/api/google-drive/sync": {}
  "/api/license/activate": {}
  "/api/license/verify": {}
  "/api/payments/sepay/checkout": {}
  "/api/payments/sepay/ipn": {}
  "/api/payments/vietqr": {}
  "/api/registration/availability": {}
  "/api/tlora/albums": {}
  "/api/tlora/edit-requests": {}
  "/api/tlora/edited-uploads": {}
  "/api/tlora/health": {}
  "/api/tlora/photos": {}
  "/api/tlora/upload": {}
  "/api/vietqr/banks": {}
  "/bang-gia": {}
  "/chinh-sach-bao-mat": {}
  "/dang-ky": {}
  "/dang-nhap": {}
  "/dich-vu": {}
  "/dieu-khoan-dich-vu": {}
  "/studio-site/[studioSlug]": { "studioSlug": string; }
  "/studio-site/[studioSlug]/quan-tri": { "studioSlug": string; }
  "/studio-site/[studioSlug]/tin-tuc": { "studioSlug": string; }
  "/studio-site/[studioSlug]/tin-tuc/[postSlug]": { "studioSlug": string; "postSlug": string; }
  "/thanh-toan/[orderId]": { "orderId": string; }
  "/tin-tuc": {}
  "/tin-tuc/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
