// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(portal)/ai-concept/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-concept">> = Specific
  const handler = {} as typeof import("../../src/app/(portal)/ai-concept/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/[customerSlug]/done/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[customerSlug]/done">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/[customerSlug]/done/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/[customerSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[customerSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/[customerSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/bang-gia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bang-gia">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/bang-gia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/chinh-sach-bao-mat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chinh-sach-bao-mat">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/chinh-sach-bao-mat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/dang-ky/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dang-ky">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/dang-ky/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/dang-nhap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dang-nhap">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/dang-nhap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/dich-vu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dich-vu">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/dich-vu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/dieu-khoan-dich-vu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dieu-khoan-dich-vu">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/dieu-khoan-dich-vu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/studio-site/[studioSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio-site/[studioSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/studio-site/[studioSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/studio-site/[studioSlug]/quan-tri/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio-site/[studioSlug]/quan-tri">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/studio-site/[studioSlug]/quan-tri/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/studio-site/[studioSlug]/tin-tuc/[postSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio-site/[studioSlug]/tin-tuc/[postSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/studio-site/[studioSlug]/tin-tuc/[postSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/studio-site/[studioSlug]/tin-tuc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio-site/[studioSlug]/tin-tuc">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/studio-site/[studioSlug]/tin-tuc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/tin-tuc/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tin-tuc/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/tin-tuc/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/tin-tuc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tin-tuc">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/tin-tuc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-studio">> = Specific
  const handler = {} as typeof import("../../src/app/admin-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/thanh-toan/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thanh-toan/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/thanh-toan/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/top-up/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/top-up">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/top-up/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/customer-galleries/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customer-galleries/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/customer-galleries/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/customer-galleries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customer-galleries">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/customer-galleries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/gmail/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/gmail/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/gmail/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/payment-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payment-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/payment-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/resolve-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/resolve-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/resolve-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-galleries/[slug]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-galleries/[slug]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-galleries/[slug]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-galleries/[slug]/payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-galleries/[slug]/payment">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-galleries/[slug]/payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-galleries/[slug]/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-galleries/[slug]/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-galleries/[slug]/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-galleries/photos/[photoId]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-galleries/photos/[photoId]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-galleries/photos/[photoId]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-galleries/photos/[photoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-galleries/photos/[photoId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-galleries/photos/[photoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google-drive/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google-drive/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/google-drive/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google-drive/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google-drive/connect">> = Specific
  const handler = {} as typeof import("../../src/app/api/google-drive/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google-drive/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google-drive/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/google-drive/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google-drive/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google-drive/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/google-drive/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/license/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/license/activate">> = Specific
  const handler = {} as typeof import("../../src/app/api/license/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/license/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/license/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/license/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/sepay/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/sepay/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/sepay/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/sepay/ipn/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/sepay/ipn">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/sepay/ipn/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/vietqr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/vietqr">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/vietqr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/registration/availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/registration/availability">> = Specific
  const handler = {} as typeof import("../../src/app/api/registration/availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tlora/albums/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tlora/albums">> = Specific
  const handler = {} as typeof import("../../src/app/api/tlora/albums/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tlora/edit-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tlora/edit-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/tlora/edit-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tlora/edited-uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tlora/edited-uploads">> = Specific
  const handler = {} as typeof import("../../src/app/api/tlora/edited-uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tlora/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tlora/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/tlora/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tlora/photos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tlora/photos">> = Specific
  const handler = {} as typeof import("../../src/app/api/tlora/photos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tlora/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tlora/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/tlora/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vietqr/banks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vietqr/banks">> = Specific
  const handler = {} as typeof import("../../src/app/api/vietqr/banks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(portal)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(portal)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
