var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/customer-galleries/route.js")
R.c("server/chunks/[root-of-the-server]__11htr_f._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/[root-of-the-server]__0qyq54v._.js")
R.c("server/chunks/src_lib_supabase_admin_ts_0cfteh4._.js")
R.c("server/chunks/[root-of-the-server]__1s93s06._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_customer-galleries_route_actions_0y9kj21.js")
R.m(92532)
module.exports=R.m(92532).exports
