var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/customer-galleries/[slug]/sync/route.js")
R.c("server/chunks/[root-of-the-server]__11htr_f._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/[root-of-the-server]__19v7sha._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/[root-of-the-server]__1s93s06._.js")
R.c("server/chunks/src_lib_supabase_admin_ts_0cfteh4._.js")
R.c("server/chunks/1oeh_server_app_api_customer-galleries_[slug]_sync_route_actions_1kqbhci.js")
R.m(79284)
module.exports=R.m(79284).exports
