var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/customer-galleries/photos/[photoId]/download/route.js")
R.c("server/chunks/[root-of-the-server]__11htr_f._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/[root-of-the-server]__1qt-b_w._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/[root-of-the-server]__1s93s06._.js")
R.c("server/chunks/src_lib_supabase_admin_ts_0cfteh4._.js")
R.c("server/chunks/1jng_app_api_customer-galleries_photos_[photoId]_download_route_actions_01awe-g.js")
R.m(32811)
module.exports=R.m(32811).exports
