var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/tlora/albums/route.js")
R.c("server/chunks/[root-of-the-server]__11htr_f._.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/[root-of-the-server]__09hxb2e._.js")
R.c("server/chunks/src_lib_supabase_admin_ts_0cfteh4._.js")
R.c("server/chunks/[root-of-the-server]__1s93s06._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/_next-internal_server_app_api_tlora_albums_route_actions_0trw33b.js")
R.m(14999)
module.exports=R.m(14999).exports
