var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/generate/route.js")
R.c("server/chunks/[externals]_next_dist_0iuj5m_._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/_17qm_ju._.js")
R.c("server/chunks/src_lib_supabase_admin_ts_0cfteh4._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_1ghxkiu.js")
R.c("server/chunks/node_modules_next_08s853w._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_generate_route_actions_1kp49s3.js")
R.m(59165)
module.exports=R.m(59165).exports
